export const MOSTRAR_BARRA = 'MOSTRAR_BARRA';
export const AGREGAR_CLASE = 'AGREGAR_CLASE';
export const ACTUALIZAR_CLASE = 'ACTUALIZAR_CLASE';
export const ELIMINAR_CLASE = 'ELIMINAR_CLASE';
export const AGREGAR_TAREA = 'AGREGAR_TAREA';
export const ACTUALIZAR_TAREA = 'ACTUALIZAR_TAREA';
export const ELIMINAR_TAREA = 'ELIMINAR_TAREA';
export const ESTADO_TAREA = 'ESTADO_TAREA';